name: Deploy to S3

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your desired region

      - name: Sync Files to S3
        run: |
          # Replace 'your-bucket-name' with your actual bucket name,
          # or use the secret: ${{ secrets.AWS_S3_BUCKET }}
          aws s3 sync . s3://your-bucket-name --delete
